services:
  gateway-service:
    image: klasshub-gateway-service
    platform: linux/amd64
    build:
      context: .
      dockerfile: services/gateway/Dockerfile.app
    container_name: ${GATEWAY_SERVICE_HOST}
    ports:
      - ${GATEWAY_SERVICE_PORT}:${GATEWAY_SERVICE_PORT}
    networks:
      - klasshub-net
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - APP_NAME=${GATEWAY_SERVICE_HOST}
      - SERVER_HOST=${GATEWAY_SERVICE_HOST}
      - SERVER_PORT=${GATEWAY_SERVICE_PORT}
      - SERVER_TIMEOUT_READ=${GATEWAY_SERVICE_TIMEOUT_READ}
      - SERVER_TIMEOUT_WRITE=${GATEWAY_SERVICE_TIMEOUT_WRITE}
      - SERVER_TIMEOUT_SHUTDOWN=${GATEWAY_SERVICE_TIMEOUT_SHUTDOWN}
      - SERVICE_AUTH_NAME=${AUTH_SERVICE_HOST}
      - SERVICE_AUTH_HOST=${AUTH_SERVICE_HOST}
      - SERVICE_AUTH_PORT=${AUTH_SERVICE_PORT}
      - TRACER_PORT=${TRACER_HTTP_PORT}
    depends_on:
      jaeger:
        condition: service_started
      auth-service:
        condition: service_started

  auth-service:
    image: klasshub-auth-service
    platform: linux/amd64
    build:
      context: .
      dockerfile: services/auth/Dockerfile.app
    container_name: ${AUTH_SERVICE_HOST}
    networks:
      - klasshub-net
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - APP_NAME=${AUTH_SERVICE_HOST}
      - SERVER_HOST=${AUTH_SERVICE_HOST}
      - SERVER_PORT=${AUTH_SERVICE_PORT}
      - SERVER_TIMEOUT_SHUTDOWN=${AUTH_SERVICE_TIMEOUT_SHUTDOWN}
      - SERVICE_USER_NAME=${USER_SERVICE_HOST}
      - SERVICE_USER_HOST=${USER_SERVICE_HOST}
      - SERVICE_USER_PORT=${USER_SERVICE_PORT}
      - SERVICE_SCHOOL_NAME=${SCHOOL_SERVICE_HOST}
      - SERVICE_SCHOOL_HOST=${SCHOOL_SERVICE_HOST}
      - SERVICE_SCHOOL_PORT=${SCHOOL_SERVICE_PORT}
      - DATABASE_HOST=${AUTH_DATABASE_HOST}
      - DATABASE_PORT=${AUTH_DATABASE_PORT}
      - DATABASE_USER=${AUTH_DATABASE_USER}
      - DATABASE_PASS=${AUTH_DATABASE_PASS}
      - DATABASE_NAME=${AUTH_DATABASE_NAME}
      - DATABASE_SSL_MODE=${AUTH_DATABASE_SSL_MODE}
      - DATABASE_MAX_CONNS=${AUTH_DATABASE_MAX_CONNS}
      - DATABASE_MIN_CONNS=${AUTH_DATABASE_MIN_CONNS}
      - DATABASE_MAX_CONN_LIFETIME=${AUTH_DATABASE_MAX_CONN_LIFETIME}
      - DATABASE_MAX_CONN_IDLE_TIME=${AUTH_DATABASE_MAX_CONN_IDLE_TIME}
      - TRACER_PORT=${TRACER_GRPC_PORT}
    depends_on:
      auth-database:
        condition: service_healthy
      auth-migrator:
        condition: service_completed_successfully

  auth-database:
    image: postgres:16-alpine
    container_name: ${AUTH_DATABASE_HOST}
    networks:
      - klasshub-net
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${AUTH_DATABASE_USER}
      - POSTGRES_PASSWORD=${AUTH_DATABASE_PASS}
      - POSTGRES_DB=${AUTH_DATABASE_NAME}
    volumes:
      - auth_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${AUTH_DATABASE_USER} -d ${AUTH_DATABASE_NAME}"]
      interval: 5s
      retries: 5

  auth-migrator:
    image: klasshub-auth-migrator
    platform: linux/amd64
    build:
      context: .
      dockerfile: services/auth/Dockerfile.migrator
    container_name: auth-migrator
    networks:
      - klasshub-net
    restart: "no"
    env_file:
      - .env
    environment:
      - DATABASE_HOST=${AUTH_DATABASE_HOST}
      - DATABASE_PORT=${AUTH_DATABASE_PORT}
      - DATABASE_USER=${AUTH_DATABASE_USER}
      - DATABASE_PASS=${AUTH_DATABASE_PASS}
      - DATABASE_NAME=${AUTH_DATABASE_NAME}
      - DATABASE_SSL_MODE=${AUTH_DATABASE_SSL_MODE}
    depends_on:
      auth-database:
        condition: service_healthy
    entrypoint: ["./bin/migrator"]
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "${AUTH_DATABASE_HOST}"]
      interval: 10s
      retries: 3

  user-service:
    image: klasshub-user-service
    platform: linux/amd64
    build:
      context: .
      dockerfile: services/user/Dockerfile.app
    container_name: ${USER_SERVICE_HOST}
    networks:
      - klasshub-net
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - APP_NAME=${USER_SERVICE_HOST}
      - SERVER_HOST=${USER_SERVICE_HOST}
      - SERVER_PORT=${USER_SERVICE_PORT}
      - SERVER_TIMEOUT_SHUTDOWN=${USER_SERVICE_TIMEOUT_SHUTDOWN}
      - DATABASE_HOST=${USER_DATABASE_HOST}
      - DATABASE_PORT=${USER_DATABASE_PORT}
      - DATABASE_USER=${USER_DATABASE_USER}
      - DATABASE_PASS=${USER_DATABASE_PASS}
      - DATABASE_NAME=${USER_DATABASE_NAME}
      - DATABASE_SSL_MODE=${USER_DATABASE_SSL_MODE}
      - DATABASE_MAX_CONNS=${USER_DATABASE_MAX_CONNS}
      - DATABASE_MIN_CONNS=${USER_DATABASE_MIN_CONNS}
      - DATABASE_MAX_CONN_LIFETIME=${USER_DATABASE_MAX_CONN_LIFETIME}
      - DATABASE_MAX_CONN_IDLE_TIME=${USER_DATABASE_MAX_CONN_IDLE_TIME}
      - TRACER_PORT=${TRACER_GRPC_PORT}
    depends_on:
      user-database:
        condition: service_healthy
      user-migrator:
        condition: service_completed_successfully

  user-database:
    image: postgres:16-alpine
    container_name: ${USER_DATABASE_HOST}
    networks:
      - klasshub-net
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${USER_DATABASE_USER}
      - POSTGRES_PASSWORD=${USER_DATABASE_PASS}
      - POSTGRES_DB=${USER_DATABASE_NAME}
    volumes:
      - user_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${USER_DATABASE_USER} -d ${USER_DATABASE_NAME}"]
      interval: 5s
      retries: 5

  user-migrator:
    image: klasshub-user-migrator
    platform: linux/amd64
    build:
      context: .
      dockerfile: services/user/Dockerfile.migrator
    container_name: user-migrator
    networks:
      - klasshub-net
    restart: "no"
    env_file:
      - .env
    environment:
      - DATABASE_HOST=${USER_DATABASE_HOST}
      - DATABASE_PORT=${USER_DATABASE_PORT}
      - DATABASE_USER=${USER_DATABASE_USER}
      - DATABASE_PASS=${USER_DATABASE_PASS}
      - DATABASE_NAME=${USER_DATABASE_NAME}
      - DATABASE_SSL_MODE=${USER_DATABASE_SSL_MODE}
    depends_on:
      user-database:
        condition: service_healthy
    entrypoint: ["./bin/migrator"]
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "${USER_DATABASE_HOST}"]
      interval: 10s
      retries: 3

  school-service:
    image: klasshub-school-service
    platform: linux/amd64
    build:
      context: .
      dockerfile: services/school/Dockerfile.app
    container_name: ${SCHOOL_SERVICE_HOST}
    networks:
      - klasshub-net
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - APP_NAME=${SCHOOL_SERVICE_HOST}
      - SERVER_HOST=${SCHOOL_SERVICE_HOST}
      - SERVER_PORT=${SCHOOL_SERVICE_PORT}
      - SERVER_TIMEOUT_SHUTDOWN=${SCHOOL_SERVICE_TIMEOUT_SHUTDOWN}
      - DATABASE_HOST=${SCHOOL_DATABASE_HOST}
      - DATABASE_PORT=${SCHOOL_DATABASE_PORT}
      - DATABASE_USER=${SCHOOL_DATABASE_USER}
      - DATABASE_PASS=${SCHOOL_DATABASE_PASS}
      - DATABASE_NAME=${SCHOOL_DATABASE_NAME}
      - DATABASE_SSL_MODE=${SCHOOL_DATABASE_SSL_MODE}
      - DATABASE_MAX_CONNS=${SCHOOL_DATABASE_MAX_CONNS}
      - DATABASE_MIN_CONNS=${SCHOOL_DATABASE_MIN_CONNS}
      - DATABASE_MAX_CONN_LIFETIME=${SCHOOL_DATABASE_MAX_CONN_LIFETIME}
      - DATABASE_MAX_CONN_IDLE_TIME=${SCHOOL_DATABASE_MAX_CONN_IDLE_TIME}
      - TRACER_PORT=${TRACER_GRPC_PORT}
    depends_on:
      school-database:
        condition: service_healthy
      school-migrator:
        condition: service_completed_successfully

  school-database:
    image: postgres:16-alpine
    container_name: ${SCHOOL_DATABASE_HOST}
    networks:
      - klasshub-net
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${SCHOOL_DATABASE_USER}
      - POSTGRES_PASSWORD=${SCHOOL_DATABASE_PASS}
      - POSTGRES_DB=${SCHOOL_DATABASE_NAME}
    volumes:
      - school_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${SCHOOL_DATABASE_USER} -d ${SCHOOL_DATABASE_NAME}"]
      interval: 5s
      retries: 5

  school-migrator:
    image: klasshub-school-migrator
    platform: linux/amd64
    build:
      context: .
      dockerfile: services/school/Dockerfile.migrator
    container_name: school-migrator
    networks:
      - klasshub-net
    restart: "no"
    env_file:
      - .env
    environment:
      - DATABASE_HOST=${SCHOOL_DATABASE_HOST}
      - DATABASE_PORT=${SCHOOL_DATABASE_PORT}
      - DATABASE_USER=${SCHOOL_DATABASE_USER}
      - DATABASE_PASS=${SCHOOL_DATABASE_PASS}
      - DATABASE_NAME=${SCHOOL_DATABASE_NAME}
      - DATABASE_SSL_MODE=${SCHOOL_DATABASE_SSL_MODE}
    depends_on:
      school-database:
        condition: service_healthy
    entrypoint: ["./bin/migrator"]
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "${SCHOOL_DATABASE_HOST}"]
      interval: 10s
      retries: 3

  # ---------- Jaeger ----------
  jaeger:
    image: jaegertracing/all-in-one:1.62.0
    container_name: ${TRACER_HOST}
    ports:
      - ${TRACER_GRPC_PORT}:${TRACER_GRPC_PORT}
      - ${TRACER_HTTP_PORT}:${TRACER_HTTP_PORT}
      - ${TRACER_WEB_UI_PORT}:${TRACER_WEB_UI_PORT}
    networks:
      - klasshub-net
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - COLLECTOR_OTLP_ENABLED=true

networks:
  klasshub-net:
    name: klasshub-net
    driver: bridge

volumes:
  auth_db_data:
  user_db_data:
  school_db_data:
