// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.2
// source: v1/account_api.proto

package apis

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateSchoolProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NPSN          *string                `protobuf:"bytes,1,opt,name=n_p_s_n,json=nPSN,proto3,oneof" json:"n_p_s_n,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Level         string                 `protobuf:"bytes,3,opt,name=level,proto3" json:"level,omitempty"`
	Ownership     string                 `protobuf:"bytes,4,opt,name=ownership,proto3" json:"ownership,omitempty"`
	Accreditation *string                `protobuf:"bytes,5,opt,name=accreditation,proto3,oneof" json:"accreditation,omitempty"`
	EstablishedAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=established_at,json=establishedAt,proto3" json:"established_at,omitempty"`
	Province      string                 `protobuf:"bytes,7,opt,name=province,proto3" json:"province,omitempty"`
	CityRegency   string                 `protobuf:"bytes,8,opt,name=city_regency,json=cityRegency,proto3" json:"city_regency,omitempty"`
	District      string                 `protobuf:"bytes,9,opt,name=district,proto3" json:"district,omitempty"`
	Subdistrict   string                 `protobuf:"bytes,10,opt,name=subdistrict,proto3" json:"subdistrict,omitempty"`
	Street        string                 `protobuf:"bytes,11,opt,name=street,proto3" json:"street,omitempty"`
	Postcode      string                 `protobuf:"bytes,12,opt,name=postcode,proto3" json:"postcode,omitempty"`
	Phone         *string                `protobuf:"bytes,13,opt,name=phone,proto3,oneof" json:"phone,omitempty"`
	Email         *string                `protobuf:"bytes,14,opt,name=email,proto3,oneof" json:"email,omitempty"`
	Website       *string                `protobuf:"bytes,15,opt,name=website,proto3,oneof" json:"website,omitempty"`
	Timezone      string                 `protobuf:"bytes,16,opt,name=timezone,proto3" json:"timezone,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,17,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSchoolProfileRequest) Reset() {
	*x = CreateSchoolProfileRequest{}
	mi := &file_v1_account_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSchoolProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSchoolProfileRequest) ProtoMessage() {}

func (x *CreateSchoolProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_account_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSchoolProfileRequest.ProtoReflect.Descriptor instead.
func (*CreateSchoolProfileRequest) Descriptor() ([]byte, []int) {
	return file_v1_account_api_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSchoolProfileRequest) GetNPSN() string {
	if x != nil && x.NPSN != nil {
		return *x.NPSN
	}
	return ""
}

func (x *CreateSchoolProfileRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateSchoolProfileRequest) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *CreateSchoolProfileRequest) GetOwnership() string {
	if x != nil {
		return x.Ownership
	}
	return ""
}

func (x *CreateSchoolProfileRequest) GetAccreditation() string {
	if x != nil && x.Accreditation != nil {
		return *x.Accreditation
	}
	return ""
}

func (x *CreateSchoolProfileRequest) GetEstablishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EstablishedAt
	}
	return nil
}

func (x *CreateSchoolProfileRequest) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *CreateSchoolProfileRequest) GetCityRegency() string {
	if x != nil {
		return x.CityRegency
	}
	return ""
}

func (x *CreateSchoolProfileRequest) GetDistrict() string {
	if x != nil {
		return x.District
	}
	return ""
}

func (x *CreateSchoolProfileRequest) GetSubdistrict() string {
	if x != nil {
		return x.Subdistrict
	}
	return ""
}

func (x *CreateSchoolProfileRequest) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *CreateSchoolProfileRequest) GetPostcode() string {
	if x != nil {
		return x.Postcode
	}
	return ""
}

func (x *CreateSchoolProfileRequest) GetPhone() string {
	if x != nil && x.Phone != nil {
		return *x.Phone
	}
	return ""
}

func (x *CreateSchoolProfileRequest) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

func (x *CreateSchoolProfileRequest) GetWebsite() string {
	if x != nil && x.Website != nil {
		return *x.Website
	}
	return ""
}

func (x *CreateSchoolProfileRequest) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

func (x *CreateSchoolProfileRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type CreateSchoolProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	School        *School                `protobuf:"bytes,1,opt,name=school,proto3" json:"school,omitempty"`
	Auth          *Auth                  `protobuf:"bytes,2,opt,name=auth,proto3" json:"auth,omitempty"`
	AuthToken     *AuthToken             `protobuf:"bytes,3,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSchoolProfileResponse) Reset() {
	*x = CreateSchoolProfileResponse{}
	mi := &file_v1_account_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSchoolProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSchoolProfileResponse) ProtoMessage() {}

func (x *CreateSchoolProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_account_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSchoolProfileResponse.ProtoReflect.Descriptor instead.
func (*CreateSchoolProfileResponse) Descriptor() ([]byte, []int) {
	return file_v1_account_api_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSchoolProfileResponse) GetSchool() *School {
	if x != nil {
		return x.School
	}
	return nil
}

func (x *CreateSchoolProfileResponse) GetAuth() *Auth {
	if x != nil {
		return x.Auth
	}
	return nil
}

func (x *CreateSchoolProfileResponse) GetAuthToken() *AuthToken {
	if x != nil {
		return x.AuthToken
	}
	return nil
}

var File_v1_account_api_proto protoreflect.FileDescriptor

const file_v1_account_api_proto_rawDesc = "" +
	"\n" +
	"\x14v1/account_api.proto\x12\n" +
	"account.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x11v1/auth_api.proto\x1a\x13v1/school_api.proto\"\xf3\x04\n" +
	"\x1aCreateSchoolProfileRequest\x12\x1a\n" +
	"\an_p_s_n\x18\x01 \x01(\tH\x00R\x04nPSN\x88\x01\x01\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05level\x18\x03 \x01(\tR\x05level\x12\x1c\n" +
	"\townership\x18\x04 \x01(\tR\townership\x12)\n" +
	"\raccreditation\x18\x05 \x01(\tH\x01R\raccreditation\x88\x01\x01\x12A\n" +
	"\x0eestablished_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\restablishedAt\x12\x1a\n" +
	"\bprovince\x18\a \x01(\tR\bprovince\x12!\n" +
	"\fcity_regency\x18\b \x01(\tR\vcityRegency\x12\x1a\n" +
	"\bdistrict\x18\t \x01(\tR\bdistrict\x12 \n" +
	"\vsubdistrict\x18\n" +
	" \x01(\tR\vsubdistrict\x12\x16\n" +
	"\x06street\x18\v \x01(\tR\x06street\x12\x1a\n" +
	"\bpostcode\x18\f \x01(\tR\bpostcode\x12\x19\n" +
	"\x05phone\x18\r \x01(\tH\x02R\x05phone\x88\x01\x01\x12\x19\n" +
	"\x05email\x18\x0e \x01(\tH\x03R\x05email\x88\x01\x01\x12\x1d\n" +
	"\awebsite\x18\x0f \x01(\tH\x04R\awebsite\x88\x01\x01\x12\x1a\n" +
	"\btimezone\x18\x10 \x01(\tR\btimezone\x12#\n" +
	"\rrefresh_token\x18\x11 \x01(\tR\frefreshTokenB\n" +
	"\n" +
	"\b_n_p_s_nB\x10\n" +
	"\x0e_accreditationB\b\n" +
	"\x06_phoneB\b\n" +
	"\x06_emailB\n" +
	"\n" +
	"\b_website\"\x9e\x01\n" +
	"\x1bCreateSchoolProfileResponse\x12)\n" +
	"\x06school\x18\x01 \x01(\v2\x11.school.v1.SchoolR\x06school\x12!\n" +
	"\x04auth\x18\x02 \x01(\v2\r.auth.v1.AuthR\x04auth\x121\n" +
	"\n" +
	"auth_token\x18\x03 \x01(\v2\x12.auth.v1.AuthTokenR\tauthToken2x\n" +
	"\x0eAccountService\x12f\n" +
	"\x13CreateSchoolProfile\x12&.account.v1.CreateSchoolProfileRequest\x1a'.account.v1.CreateSchoolProfileResponseBAZ?github.com/ritchieridanko/klasshub/shared/contract/apis/v1;apisb\x06proto3"

var (
	file_v1_account_api_proto_rawDescOnce sync.Once
	file_v1_account_api_proto_rawDescData []byte
)

func file_v1_account_api_proto_rawDescGZIP() []byte {
	file_v1_account_api_proto_rawDescOnce.Do(func() {
		file_v1_account_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_account_api_proto_rawDesc), len(file_v1_account_api_proto_rawDesc)))
	})
	return file_v1_account_api_proto_rawDescData
}

var file_v1_account_api_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_v1_account_api_proto_goTypes = []any{
	(*CreateSchoolProfileRequest)(nil),  // 0: account.v1.CreateSchoolProfileRequest
	(*CreateSchoolProfileResponse)(nil), // 1: account.v1.CreateSchoolProfileResponse
	(*timestamppb.Timestamp)(nil),       // 2: google.protobuf.Timestamp
	(*School)(nil),                      // 3: school.v1.School
	(*Auth)(nil),                        // 4: auth.v1.Auth
	(*AuthToken)(nil),                   // 5: auth.v1.AuthToken
}
var file_v1_account_api_proto_depIdxs = []int32{
	2, // 0: account.v1.CreateSchoolProfileRequest.established_at:type_name -> google.protobuf.Timestamp
	3, // 1: account.v1.CreateSchoolProfileResponse.school:type_name -> school.v1.School
	4, // 2: account.v1.CreateSchoolProfileResponse.auth:type_name -> auth.v1.Auth
	5, // 3: account.v1.CreateSchoolProfileResponse.auth_token:type_name -> auth.v1.AuthToken
	0, // 4: account.v1.AccountService.CreateSchoolProfile:input_type -> account.v1.CreateSchoolProfileRequest
	1, // 5: account.v1.AccountService.CreateSchoolProfile:output_type -> account.v1.CreateSchoolProfileResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_v1_account_api_proto_init() }
func file_v1_account_api_proto_init() {
	if File_v1_account_api_proto != nil {
		return
	}
	file_v1_auth_api_proto_init()
	file_v1_school_api_proto_init()
	file_v1_account_api_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_account_api_proto_rawDesc), len(file_v1_account_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_account_api_proto_goTypes,
		DependencyIndexes: file_v1_account_api_proto_depIdxs,
		MessageInfos:      file_v1_account_api_proto_msgTypes,
	}.Build()
	File_v1_account_api_proto = out.File
	file_v1_account_api_proto_goTypes = nil
	file_v1_account_api_proto_depIdxs = nil
}
