// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.2
// source: v1/auth_api.proto

package apis

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Auth struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Email             *string                `protobuf:"bytes,1,opt,name=email,proto3,oneof" json:"email,omitempty"`
	Username          *string                `protobuf:"bytes,2,opt,name=username,proto3,oneof" json:"username,omitempty"`
	Role              string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	IsVerified        bool                   `protobuf:"varint,4,opt,name=is_verified,json=isVerified,proto3" json:"is_verified,omitempty"`
	SchoolExists      bool                   `protobuf:"varint,5,opt,name=school_exists,json=schoolExists,proto3" json:"school_exists,omitempty"`
	PasswordChangedAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=password_changed_at,json=passwordChangedAt,proto3" json:"password_changed_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Auth) Reset() {
	*x = Auth{}
	mi := &file_v1_auth_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Auth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Auth) ProtoMessage() {}

func (x *Auth) ProtoReflect() protoreflect.Message {
	mi := &file_v1_auth_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Auth.ProtoReflect.Descriptor instead.
func (*Auth) Descriptor() ([]byte, []int) {
	return file_v1_auth_api_proto_rawDescGZIP(), []int{0}
}

func (x *Auth) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

func (x *Auth) GetUsername() string {
	if x != nil && x.Username != nil {
		return *x.Username
	}
	return ""
}

func (x *Auth) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Auth) GetIsVerified() bool {
	if x != nil {
		return x.IsVerified
	}
	return false
}

func (x *Auth) GetSchoolExists() bool {
	if x != nil {
		return x.SchoolExists
	}
	return false
}

func (x *Auth) GetPasswordChangedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PasswordChangedAt
	}
	return nil
}

type AccessToken struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	ExpiresIn     int64                  `protobuf:"varint,2,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"` // seconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessToken) Reset() {
	*x = AccessToken{}
	mi := &file_v1_auth_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessToken) ProtoMessage() {}

func (x *AccessToken) ProtoReflect() protoreflect.Message {
	mi := &file_v1_auth_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessToken.ProtoReflect.Descriptor instead.
func (*AccessToken) Descriptor() ([]byte, []int) {
	return file_v1_auth_api_proto_rawDescGZIP(), []int{1}
}

func (x *AccessToken) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AccessToken) GetExpiresIn() int64 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

type RefreshToken struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	ExpiresIn     int64                  `protobuf:"varint,2,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"` // seconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshToken) Reset() {
	*x = RefreshToken{}
	mi := &file_v1_auth_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshToken) ProtoMessage() {}

func (x *RefreshToken) ProtoReflect() protoreflect.Message {
	mi := &file_v1_auth_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshToken.ProtoReflect.Descriptor instead.
func (*RefreshToken) Descriptor() ([]byte, []int) {
	return file_v1_auth_api_proto_rawDescGZIP(), []int{2}
}

func (x *RefreshToken) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RefreshToken) GetExpiresIn() int64 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

type AuthToken struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   *AccessToken           `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  *RefreshToken          `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthToken) Reset() {
	*x = AuthToken{}
	mi := &file_v1_auth_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthToken) ProtoMessage() {}

func (x *AuthToken) ProtoReflect() protoreflect.Message {
	mi := &file_v1_auth_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthToken.ProtoReflect.Descriptor instead.
func (*AuthToken) Descriptor() ([]byte, []int) {
	return file_v1_auth_api_proto_rawDescGZIP(), []int{3}
}

func (x *AuthToken) GetAccessToken() *AccessToken {
	if x != nil {
		return x.AccessToken
	}
	return nil
}

func (x *AuthToken) GetRefreshToken() *RefreshToken {
	if x != nil {
		return x.RefreshToken
	}
	return nil
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identifier    string                 `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_v1_auth_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_auth_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_v1_auth_api_proto_rawDescGZIP(), []int{4}
}

func (x *LoginRequest) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Auth          *Auth                  `protobuf:"bytes,1,opt,name=auth,proto3" json:"auth,omitempty"`
	AuthToken     *AuthToken             `protobuf:"bytes,2,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_v1_auth_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_auth_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_v1_auth_api_proto_rawDescGZIP(), []int{5}
}

func (x *LoginResponse) GetAuth() *Auth {
	if x != nil {
		return x.Auth
	}
	return nil
}

func (x *LoginResponse) GetAuthToken() *AuthToken {
	if x != nil {
		return x.AuthToken
	}
	return nil
}

type LogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_v1_auth_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_auth_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_v1_auth_api_proto_rawDescGZIP(), []int{6}
}

func (x *LogoutRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type CreateSchoolAuthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSchoolAuthRequest) Reset() {
	*x = CreateSchoolAuthRequest{}
	mi := &file_v1_auth_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSchoolAuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSchoolAuthRequest) ProtoMessage() {}

func (x *CreateSchoolAuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_auth_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSchoolAuthRequest.ProtoReflect.Descriptor instead.
func (*CreateSchoolAuthRequest) Descriptor() ([]byte, []int) {
	return file_v1_auth_api_proto_rawDescGZIP(), []int{7}
}

func (x *CreateSchoolAuthRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateSchoolAuthRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type CreateSchoolAuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Auth          *Auth                  `protobuf:"bytes,1,opt,name=auth,proto3" json:"auth,omitempty"`
	AuthToken     *AuthToken             `protobuf:"bytes,2,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSchoolAuthResponse) Reset() {
	*x = CreateSchoolAuthResponse{}
	mi := &file_v1_auth_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSchoolAuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSchoolAuthResponse) ProtoMessage() {}

func (x *CreateSchoolAuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_auth_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSchoolAuthResponse.ProtoReflect.Descriptor instead.
func (*CreateSchoolAuthResponse) Descriptor() ([]byte, []int) {
	return file_v1_auth_api_proto_rawDescGZIP(), []int{8}
}

func (x *CreateSchoolAuthResponse) GetAuth() *Auth {
	if x != nil {
		return x.Auth
	}
	return nil
}

func (x *CreateSchoolAuthResponse) GetAuthToken() *AuthToken {
	if x != nil {
		return x.AuthToken
	}
	return nil
}

type UpdateSchoolRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchoolId      int64                  `protobuf:"varint,1,opt,name=school_id,json=schoolId,proto3" json:"school_id,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSchoolRequest) Reset() {
	*x = UpdateSchoolRequest{}
	mi := &file_v1_auth_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSchoolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSchoolRequest) ProtoMessage() {}

func (x *UpdateSchoolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_auth_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSchoolRequest.ProtoReflect.Descriptor instead.
func (*UpdateSchoolRequest) Descriptor() ([]byte, []int) {
	return file_v1_auth_api_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateSchoolRequest) GetSchoolId() int64 {
	if x != nil {
		return x.SchoolId
	}
	return 0
}

func (x *UpdateSchoolRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type UpdateSchoolResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Auth          *Auth                  `protobuf:"bytes,1,opt,name=auth,proto3" json:"auth,omitempty"`
	AuthToken     *AuthToken             `protobuf:"bytes,2,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSchoolResponse) Reset() {
	*x = UpdateSchoolResponse{}
	mi := &file_v1_auth_api_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSchoolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSchoolResponse) ProtoMessage() {}

func (x *UpdateSchoolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_auth_api_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSchoolResponse.ProtoReflect.Descriptor instead.
func (*UpdateSchoolResponse) Descriptor() ([]byte, []int) {
	return file_v1_auth_api_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateSchoolResponse) GetAuth() *Auth {
	if x != nil {
		return x.Auth
	}
	return nil
}

func (x *UpdateSchoolResponse) GetAuthToken() *AuthToken {
	if x != nil {
		return x.AuthToken
	}
	return nil
}

type ChangePasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OldPassword   string                 `protobuf:"bytes,1,opt,name=old_password,json=oldPassword,proto3" json:"old_password,omitempty"`
	NewPassword   string                 `protobuf:"bytes,2,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangePasswordRequest) Reset() {
	*x = ChangePasswordRequest{}
	mi := &file_v1_auth_api_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangePasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePasswordRequest) ProtoMessage() {}

func (x *ChangePasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_auth_api_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangePasswordRequest.ProtoReflect.Descriptor instead.
func (*ChangePasswordRequest) Descriptor() ([]byte, []int) {
	return file_v1_auth_api_proto_rawDescGZIP(), []int{11}
}

func (x *ChangePasswordRequest) GetOldPassword() string {
	if x != nil {
		return x.OldPassword
	}
	return ""
}

func (x *ChangePasswordRequest) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

type ChangePasswordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Auth          *Auth                  `protobuf:"bytes,1,opt,name=auth,proto3" json:"auth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangePasswordResponse) Reset() {
	*x = ChangePasswordResponse{}
	mi := &file_v1_auth_api_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangePasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePasswordResponse) ProtoMessage() {}

func (x *ChangePasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_auth_api_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangePasswordResponse.ProtoReflect.Descriptor instead.
func (*ChangePasswordResponse) Descriptor() ([]byte, []int) {
	return file_v1_auth_api_proto_rawDescGZIP(), []int{12}
}

func (x *ChangePasswordResponse) GetAuth() *Auth {
	if x != nil {
		return x.Auth
	}
	return nil
}

type ResendVerificationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResendVerificationResponse) Reset() {
	*x = ResendVerificationResponse{}
	mi := &file_v1_auth_api_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResendVerificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResendVerificationResponse) ProtoMessage() {}

func (x *ResendVerificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_auth_api_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResendVerificationResponse.ProtoReflect.Descriptor instead.
func (*ResendVerificationResponse) Descriptor() ([]byte, []int) {
	return file_v1_auth_api_proto_rawDescGZIP(), []int{13}
}

func (x *ResendVerificationResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type VerifyEmailRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	VerificationToken string                 `protobuf:"bytes,1,opt,name=verification_token,json=verificationToken,proto3" json:"verification_token,omitempty"`
	RefreshToken      string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *VerifyEmailRequest) Reset() {
	*x = VerifyEmailRequest{}
	mi := &file_v1_auth_api_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyEmailRequest) ProtoMessage() {}

func (x *VerifyEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_auth_api_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyEmailRequest.ProtoReflect.Descriptor instead.
func (*VerifyEmailRequest) Descriptor() ([]byte, []int) {
	return file_v1_auth_api_proto_rawDescGZIP(), []int{14}
}

func (x *VerifyEmailRequest) GetVerificationToken() string {
	if x != nil {
		return x.VerificationToken
	}
	return ""
}

func (x *VerifyEmailRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type VerifyEmailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Auth          *Auth                  `protobuf:"bytes,1,opt,name=auth,proto3" json:"auth,omitempty"`
	AuthToken     *AuthToken             `protobuf:"bytes,2,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyEmailResponse) Reset() {
	*x = VerifyEmailResponse{}
	mi := &file_v1_auth_api_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyEmailResponse) ProtoMessage() {}

func (x *VerifyEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_auth_api_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyEmailResponse.ProtoReflect.Descriptor instead.
func (*VerifyEmailResponse) Descriptor() ([]byte, []int) {
	return file_v1_auth_api_proto_rawDescGZIP(), []int{15}
}

func (x *VerifyEmailResponse) GetAuth() *Auth {
	if x != nil {
		return x.Auth
	}
	return nil
}

func (x *VerifyEmailResponse) GetAuthToken() *AuthToken {
	if x != nil {
		return x.AuthToken
	}
	return nil
}

type RotateAuthTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RotateAuthTokenRequest) Reset() {
	*x = RotateAuthTokenRequest{}
	mi := &file_v1_auth_api_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotateAuthTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotateAuthTokenRequest) ProtoMessage() {}

func (x *RotateAuthTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_auth_api_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotateAuthTokenRequest.ProtoReflect.Descriptor instead.
func (*RotateAuthTokenRequest) Descriptor() ([]byte, []int) {
	return file_v1_auth_api_proto_rawDescGZIP(), []int{16}
}

func (x *RotateAuthTokenRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type RotateAuthTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthToken     *AuthToken             `protobuf:"bytes,1,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RotateAuthTokenResponse) Reset() {
	*x = RotateAuthTokenResponse{}
	mi := &file_v1_auth_api_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotateAuthTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotateAuthTokenResponse) ProtoMessage() {}

func (x *RotateAuthTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_auth_api_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotateAuthTokenResponse.ProtoReflect.Descriptor instead.
func (*RotateAuthTokenResponse) Descriptor() ([]byte, []int) {
	return file_v1_auth_api_proto_rawDescGZIP(), []int{17}
}

func (x *RotateAuthTokenResponse) GetAuthToken() *AuthToken {
	if x != nil {
		return x.AuthToken
	}
	return nil
}

type EmailAvailabilityCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmailAvailabilityCheckRequest) Reset() {
	*x = EmailAvailabilityCheckRequest{}
	mi := &file_v1_auth_api_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailAvailabilityCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailAvailabilityCheckRequest) ProtoMessage() {}

func (x *EmailAvailabilityCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_auth_api_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailAvailabilityCheckRequest.ProtoReflect.Descriptor instead.
func (*EmailAvailabilityCheckRequest) Descriptor() ([]byte, []int) {
	return file_v1_auth_api_proto_rawDescGZIP(), []int{18}
}

func (x *EmailAvailabilityCheckRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type EmailAvailabilityCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsAvailable   bool                   `protobuf:"varint,1,opt,name=is_available,json=isAvailable,proto3" json:"is_available,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmailAvailabilityCheckResponse) Reset() {
	*x = EmailAvailabilityCheckResponse{}
	mi := &file_v1_auth_api_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailAvailabilityCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailAvailabilityCheckResponse) ProtoMessage() {}

func (x *EmailAvailabilityCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_auth_api_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailAvailabilityCheckResponse.ProtoReflect.Descriptor instead.
func (*EmailAvailabilityCheckResponse) Descriptor() ([]byte, []int) {
	return file_v1_auth_api_proto_rawDescGZIP(), []int{19}
}

func (x *EmailAvailabilityCheckResponse) GetIsAvailable() bool {
	if x != nil {
		return x.IsAvailable
	}
	return false
}

var File_v1_auth_api_proto protoreflect.FileDescriptor

const file_v1_auth_api_proto_rawDesc = "" +
	"\n" +
	"\x11v1/auth_api.proto\x12\aauth.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xff\x01\n" +
	"\x04Auth\x12\x19\n" +
	"\x05email\x18\x01 \x01(\tH\x00R\x05email\x88\x01\x01\x12\x1f\n" +
	"\busername\x18\x02 \x01(\tH\x01R\busername\x88\x01\x01\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x12\x1f\n" +
	"\vis_verified\x18\x04 \x01(\bR\n" +
	"isVerified\x12#\n" +
	"\rschool_exists\x18\x05 \x01(\bR\fschoolExists\x12J\n" +
	"\x13password_changed_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x11passwordChangedAtB\b\n" +
	"\x06_emailB\v\n" +
	"\t_username\"B\n" +
	"\vAccessToken\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x02 \x01(\x03R\texpiresIn\"C\n" +
	"\fRefreshToken\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x02 \x01(\x03R\texpiresIn\"\x80\x01\n" +
	"\tAuthToken\x127\n" +
	"\faccess_token\x18\x01 \x01(\v2\x14.auth.v1.AccessTokenR\vaccessToken\x12:\n" +
	"\rrefresh_token\x18\x02 \x01(\v2\x15.auth.v1.RefreshTokenR\frefreshToken\"J\n" +
	"\fLoginRequest\x12\x1e\n" +
	"\n" +
	"identifier\x18\x01 \x01(\tR\n" +
	"identifier\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"e\n" +
	"\rLoginResponse\x12!\n" +
	"\x04auth\x18\x01 \x01(\v2\r.auth.v1.AuthR\x04auth\x121\n" +
	"\n" +
	"auth_token\x18\x02 \x01(\v2\x12.auth.v1.AuthTokenR\tauthToken\"4\n" +
	"\rLogoutRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"K\n" +
	"\x17CreateSchoolAuthRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"p\n" +
	"\x18CreateSchoolAuthResponse\x12!\n" +
	"\x04auth\x18\x01 \x01(\v2\r.auth.v1.AuthR\x04auth\x121\n" +
	"\n" +
	"auth_token\x18\x02 \x01(\v2\x12.auth.v1.AuthTokenR\tauthToken\"W\n" +
	"\x13UpdateSchoolRequest\x12\x1b\n" +
	"\tschool_id\x18\x01 \x01(\x03R\bschoolId\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\"l\n" +
	"\x14UpdateSchoolResponse\x12!\n" +
	"\x04auth\x18\x01 \x01(\v2\r.auth.v1.AuthR\x04auth\x121\n" +
	"\n" +
	"auth_token\x18\x02 \x01(\v2\x12.auth.v1.AuthTokenR\tauthToken\"]\n" +
	"\x15ChangePasswordRequest\x12!\n" +
	"\fold_password\x18\x01 \x01(\tR\voldPassword\x12!\n" +
	"\fnew_password\x18\x02 \x01(\tR\vnewPassword\";\n" +
	"\x16ChangePasswordResponse\x12!\n" +
	"\x04auth\x18\x01 \x01(\v2\r.auth.v1.AuthR\x04auth\"2\n" +
	"\x1aResendVerificationResponse\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"h\n" +
	"\x12VerifyEmailRequest\x12-\n" +
	"\x12verification_token\x18\x01 \x01(\tR\x11verificationToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\"k\n" +
	"\x13VerifyEmailResponse\x12!\n" +
	"\x04auth\x18\x01 \x01(\v2\r.auth.v1.AuthR\x04auth\x121\n" +
	"\n" +
	"auth_token\x18\x02 \x01(\v2\x12.auth.v1.AuthTokenR\tauthToken\"=\n" +
	"\x16RotateAuthTokenRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"L\n" +
	"\x17RotateAuthTokenResponse\x121\n" +
	"\n" +
	"auth_token\x18\x01 \x01(\v2\x12.auth.v1.AuthTokenR\tauthToken\"5\n" +
	"\x1dEmailAvailabilityCheckRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"C\n" +
	"\x1eEmailAvailabilityCheckResponse\x12!\n" +
	"\fis_available\x18\x01 \x01(\bR\visAvailable2\xd0\x05\n" +
	"\vAuthService\x126\n" +
	"\x05Login\x12\x15.auth.v1.LoginRequest\x1a\x16.auth.v1.LoginResponse\x128\n" +
	"\x06Logout\x12\x16.auth.v1.LogoutRequest\x1a\x16.google.protobuf.Empty\x12W\n" +
	"\x10CreateSchoolAuth\x12 .auth.v1.CreateSchoolAuthRequest\x1a!.auth.v1.CreateSchoolAuthResponse\x12K\n" +
	"\fUpdateSchool\x12\x1c.auth.v1.UpdateSchoolRequest\x1a\x1d.auth.v1.UpdateSchoolResponse\x12Q\n" +
	"\x0eChangePassword\x12\x1e.auth.v1.ChangePasswordRequest\x1a\x1f.auth.v1.ChangePasswordResponse\x12Q\n" +
	"\x12ResendVerification\x12\x16.google.protobuf.Empty\x1a#.auth.v1.ResendVerificationResponse\x12H\n" +
	"\vVerifyEmail\x12\x1b.auth.v1.VerifyEmailRequest\x1a\x1c.auth.v1.VerifyEmailResponse\x12T\n" +
	"\x0fRotateAuthToken\x12\x1f.auth.v1.RotateAuthTokenRequest\x1a .auth.v1.RotateAuthTokenResponse\x12c\n" +
	"\x10IsEmailAvailable\x12&.auth.v1.EmailAvailabilityCheckRequest\x1a'.auth.v1.EmailAvailabilityCheckResponseBAZ?github.com/ritchieridanko/klasshub/shared/contract/apis/v1;apisb\x06proto3"

var (
	file_v1_auth_api_proto_rawDescOnce sync.Once
	file_v1_auth_api_proto_rawDescData []byte
)

func file_v1_auth_api_proto_rawDescGZIP() []byte {
	file_v1_auth_api_proto_rawDescOnce.Do(func() {
		file_v1_auth_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_auth_api_proto_rawDesc), len(file_v1_auth_api_proto_rawDesc)))
	})
	return file_v1_auth_api_proto_rawDescData
}

var file_v1_auth_api_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_v1_auth_api_proto_goTypes = []any{
	(*Auth)(nil),                           // 0: auth.v1.Auth
	(*AccessToken)(nil),                    // 1: auth.v1.AccessToken
	(*RefreshToken)(nil),                   // 2: auth.v1.RefreshToken
	(*AuthToken)(nil),                      // 3: auth.v1.AuthToken
	(*LoginRequest)(nil),                   // 4: auth.v1.LoginRequest
	(*LoginResponse)(nil),                  // 5: auth.v1.LoginResponse
	(*LogoutRequest)(nil),                  // 6: auth.v1.LogoutRequest
	(*CreateSchoolAuthRequest)(nil),        // 7: auth.v1.CreateSchoolAuthRequest
	(*CreateSchoolAuthResponse)(nil),       // 8: auth.v1.CreateSchoolAuthResponse
	(*UpdateSchoolRequest)(nil),            // 9: auth.v1.UpdateSchoolRequest
	(*UpdateSchoolResponse)(nil),           // 10: auth.v1.UpdateSchoolResponse
	(*ChangePasswordRequest)(nil),          // 11: auth.v1.ChangePasswordRequest
	(*ChangePasswordResponse)(nil),         // 12: auth.v1.ChangePasswordResponse
	(*ResendVerificationResponse)(nil),     // 13: auth.v1.ResendVerificationResponse
	(*VerifyEmailRequest)(nil),             // 14: auth.v1.VerifyEmailRequest
	(*VerifyEmailResponse)(nil),            // 15: auth.v1.VerifyEmailResponse
	(*RotateAuthTokenRequest)(nil),         // 16: auth.v1.RotateAuthTokenRequest
	(*RotateAuthTokenResponse)(nil),        // 17: auth.v1.RotateAuthTokenResponse
	(*EmailAvailabilityCheckRequest)(nil),  // 18: auth.v1.EmailAvailabilityCheckRequest
	(*EmailAvailabilityCheckResponse)(nil), // 19: auth.v1.EmailAvailabilityCheckResponse
	(*timestamppb.Timestamp)(nil),          // 20: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                  // 21: google.protobuf.Empty
}
var file_v1_auth_api_proto_depIdxs = []int32{
	20, // 0: auth.v1.Auth.password_changed_at:type_name -> google.protobuf.Timestamp
	1,  // 1: auth.v1.AuthToken.access_token:type_name -> auth.v1.AccessToken
	2,  // 2: auth.v1.AuthToken.refresh_token:type_name -> auth.v1.RefreshToken
	0,  // 3: auth.v1.LoginResponse.auth:type_name -> auth.v1.Auth
	3,  // 4: auth.v1.LoginResponse.auth_token:type_name -> auth.v1.AuthToken
	0,  // 5: auth.v1.CreateSchoolAuthResponse.auth:type_name -> auth.v1.Auth
	3,  // 6: auth.v1.CreateSchoolAuthResponse.auth_token:type_name -> auth.v1.AuthToken
	0,  // 7: auth.v1.UpdateSchoolResponse.auth:type_name -> auth.v1.Auth
	3,  // 8: auth.v1.UpdateSchoolResponse.auth_token:type_name -> auth.v1.AuthToken
	0,  // 9: auth.v1.ChangePasswordResponse.auth:type_name -> auth.v1.Auth
	0,  // 10: auth.v1.VerifyEmailResponse.auth:type_name -> auth.v1.Auth
	3,  // 11: auth.v1.VerifyEmailResponse.auth_token:type_name -> auth.v1.AuthToken
	3,  // 12: auth.v1.RotateAuthTokenResponse.auth_token:type_name -> auth.v1.AuthToken
	4,  // 13: auth.v1.AuthService.Login:input_type -> auth.v1.LoginRequest
	6,  // 14: auth.v1.AuthService.Logout:input_type -> auth.v1.LogoutRequest
	7,  // 15: auth.v1.AuthService.CreateSchoolAuth:input_type -> auth.v1.CreateSchoolAuthRequest
	9,  // 16: auth.v1.AuthService.UpdateSchool:input_type -> auth.v1.UpdateSchoolRequest
	11, // 17: auth.v1.AuthService.ChangePassword:input_type -> auth.v1.ChangePasswordRequest
	21, // 18: auth.v1.AuthService.ResendVerification:input_type -> google.protobuf.Empty
	14, // 19: auth.v1.AuthService.VerifyEmail:input_type -> auth.v1.VerifyEmailRequest
	16, // 20: auth.v1.AuthService.RotateAuthToken:input_type -> auth.v1.RotateAuthTokenRequest
	18, // 21: auth.v1.AuthService.IsEmailAvailable:input_type -> auth.v1.EmailAvailabilityCheckRequest
	5,  // 22: auth.v1.AuthService.Login:output_type -> auth.v1.LoginResponse
	21, // 23: auth.v1.AuthService.Logout:output_type -> google.protobuf.Empty
	8,  // 24: auth.v1.AuthService.CreateSchoolAuth:output_type -> auth.v1.CreateSchoolAuthResponse
	10, // 25: auth.v1.AuthService.UpdateSchool:output_type -> auth.v1.UpdateSchoolResponse
	12, // 26: auth.v1.AuthService.ChangePassword:output_type -> auth.v1.ChangePasswordResponse
	13, // 27: auth.v1.AuthService.ResendVerification:output_type -> auth.v1.ResendVerificationResponse
	15, // 28: auth.v1.AuthService.VerifyEmail:output_type -> auth.v1.VerifyEmailResponse
	17, // 29: auth.v1.AuthService.RotateAuthToken:output_type -> auth.v1.RotateAuthTokenResponse
	19, // 30: auth.v1.AuthService.IsEmailAvailable:output_type -> auth.v1.EmailAvailabilityCheckResponse
	22, // [22:31] is the sub-list for method output_type
	13, // [13:22] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_v1_auth_api_proto_init() }
func file_v1_auth_api_proto_init() {
	if File_v1_auth_api_proto != nil {
		return
	}
	file_v1_auth_api_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_auth_api_proto_rawDesc), len(file_v1_auth_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_auth_api_proto_goTypes,
		DependencyIndexes: file_v1_auth_api_proto_depIdxs,
		MessageInfos:      file_v1_auth_api_proto_msgTypes,
	}.Build()
	File_v1_auth_api_proto = out.File
	file_v1_auth_api_proto_goTypes = nil
	file_v1_auth_api_proto_depIdxs = nil
}
