// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.2
// source: v1/course_api.proto

package apis

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Course struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SchoolCourseId *string                `protobuf:"bytes,2,opt,name=school_course_id,json=schoolCourseId,proto3,oneof" json:"school_course_id,omitempty"`
	Name           string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description    *string                `protobuf:"bytes,4,opt,name=description,proto3,oneof" json:"description,omitempty"`
	CoursePicture  *string                `protobuf:"bytes,5,opt,name=course_picture,json=coursePicture,proto3,oneof" json:"course_picture,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Course) Reset() {
	*x = Course{}
	mi := &file_v1_course_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Course) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Course) ProtoMessage() {}

func (x *Course) ProtoReflect() protoreflect.Message {
	mi := &file_v1_course_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Course.ProtoReflect.Descriptor instead.
func (*Course) Descriptor() ([]byte, []int) {
	return file_v1_course_api_proto_rawDescGZIP(), []int{0}
}

func (x *Course) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Course) GetSchoolCourseId() string {
	if x != nil && x.SchoolCourseId != nil {
		return *x.SchoolCourseId
	}
	return ""
}

func (x *Course) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Course) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *Course) GetCoursePicture() string {
	if x != nil && x.CoursePicture != nil {
		return *x.CoursePicture
	}
	return ""
}

func (x *Course) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Course) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateCourseRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SchoolCourseId *string                `protobuf:"bytes,1,opt,name=school_course_id,json=schoolCourseId,proto3,oneof" json:"school_course_id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description    *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	CoursePicture  *string                `protobuf:"bytes,4,opt,name=course_picture,json=coursePicture,proto3,oneof" json:"course_picture,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateCourseRequest) Reset() {
	*x = CreateCourseRequest{}
	mi := &file_v1_course_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCourseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCourseRequest) ProtoMessage() {}

func (x *CreateCourseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_course_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCourseRequest.ProtoReflect.Descriptor instead.
func (*CreateCourseRequest) Descriptor() ([]byte, []int) {
	return file_v1_course_api_proto_rawDescGZIP(), []int{1}
}

func (x *CreateCourseRequest) GetSchoolCourseId() string {
	if x != nil && x.SchoolCourseId != nil {
		return *x.SchoolCourseId
	}
	return ""
}

func (x *CreateCourseRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateCourseRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *CreateCourseRequest) GetCoursePicture() string {
	if x != nil && x.CoursePicture != nil {
		return *x.CoursePicture
	}
	return ""
}

type CreateCourseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Course        *Course                `protobuf:"bytes,1,opt,name=course,proto3" json:"course,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCourseResponse) Reset() {
	*x = CreateCourseResponse{}
	mi := &file_v1_course_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCourseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCourseResponse) ProtoMessage() {}

func (x *CreateCourseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_course_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCourseResponse.ProtoReflect.Descriptor instead.
func (*CreateCourseResponse) Descriptor() ([]byte, []int) {
	return file_v1_course_api_proto_rawDescGZIP(), []int{2}
}

func (x *CreateCourseResponse) GetCourse() *Course {
	if x != nil {
		return x.Course
	}
	return nil
}

var File_v1_course_api_proto protoreflect.FileDescriptor

const file_v1_course_api_proto_rawDesc = "" +
	"\n" +
	"\x13v1/course_api.proto\x12\tcourse.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xdc\x02\n" +
	"\x06Course\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12-\n" +
	"\x10school_course_id\x18\x02 \x01(\tH\x00R\x0eschoolCourseId\x88\x01\x01\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12%\n" +
	"\vdescription\x18\x04 \x01(\tH\x01R\vdescription\x88\x01\x01\x12*\n" +
	"\x0ecourse_picture\x18\x05 \x01(\tH\x02R\rcoursePicture\x88\x01\x01\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB\x13\n" +
	"\x11_school_course_idB\x0e\n" +
	"\f_descriptionB\x11\n" +
	"\x0f_course_picture\"\xe3\x01\n" +
	"\x13CreateCourseRequest\x12-\n" +
	"\x10school_course_id\x18\x01 \x01(\tH\x00R\x0eschoolCourseId\x88\x01\x01\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x01R\vdescription\x88\x01\x01\x12*\n" +
	"\x0ecourse_picture\x18\x04 \x01(\tH\x02R\rcoursePicture\x88\x01\x01B\x13\n" +
	"\x11_school_course_idB\x0e\n" +
	"\f_descriptionB\x11\n" +
	"\x0f_course_picture\"A\n" +
	"\x14CreateCourseResponse\x12)\n" +
	"\x06course\x18\x01 \x01(\v2\x11.course.v1.CourseR\x06course2`\n" +
	"\rCourseService\x12O\n" +
	"\fCreateCourse\x12\x1e.course.v1.CreateCourseRequest\x1a\x1f.course.v1.CreateCourseResponseBAZ?github.com/ritchieridanko/klasshub/shared/contract/apis/v1;apisb\x06proto3"

var (
	file_v1_course_api_proto_rawDescOnce sync.Once
	file_v1_course_api_proto_rawDescData []byte
)

func file_v1_course_api_proto_rawDescGZIP() []byte {
	file_v1_course_api_proto_rawDescOnce.Do(func() {
		file_v1_course_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_course_api_proto_rawDesc), len(file_v1_course_api_proto_rawDesc)))
	})
	return file_v1_course_api_proto_rawDescData
}

var file_v1_course_api_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_v1_course_api_proto_goTypes = []any{
	(*Course)(nil),                // 0: course.v1.Course
	(*CreateCourseRequest)(nil),   // 1: course.v1.CreateCourseRequest
	(*CreateCourseResponse)(nil),  // 2: course.v1.CreateCourseResponse
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_v1_course_api_proto_depIdxs = []int32{
	3, // 0: course.v1.Course.created_at:type_name -> google.protobuf.Timestamp
	3, // 1: course.v1.Course.updated_at:type_name -> google.protobuf.Timestamp
	0, // 2: course.v1.CreateCourseResponse.course:type_name -> course.v1.Course
	1, // 3: course.v1.CourseService.CreateCourse:input_type -> course.v1.CreateCourseRequest
	2, // 4: course.v1.CourseService.CreateCourse:output_type -> course.v1.CreateCourseResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_v1_course_api_proto_init() }
func file_v1_course_api_proto_init() {
	if File_v1_course_api_proto != nil {
		return
	}
	file_v1_course_api_proto_msgTypes[0].OneofWrappers = []any{}
	file_v1_course_api_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_course_api_proto_rawDesc), len(file_v1_course_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_course_api_proto_goTypes,
		DependencyIndexes: file_v1_course_api_proto_depIdxs,
		MessageInfos:      file_v1_course_api_proto_msgTypes,
	}.Build()
	File_v1_course_api_proto = out.File
	file_v1_course_api_proto_goTypes = nil
	file_v1_course_api_proto_depIdxs = nil
}
