// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.2
// source: v1/school_api.proto

package apis

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetSchoolIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthId        int64                  `protobuf:"varint,1,opt,name=auth_id,json=authId,proto3" json:"auth_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSchoolIDRequest) Reset() {
	*x = GetSchoolIDRequest{}
	mi := &file_v1_school_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSchoolIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSchoolIDRequest) ProtoMessage() {}

func (x *GetSchoolIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_school_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSchoolIDRequest.ProtoReflect.Descriptor instead.
func (*GetSchoolIDRequest) Descriptor() ([]byte, []int) {
	return file_v1_school_api_proto_rawDescGZIP(), []int{0}
}

func (x *GetSchoolIDRequest) GetAuthId() int64 {
	if x != nil {
		return x.AuthId
	}
	return 0
}

type GetSchoolIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchoolId      int64                  `protobuf:"varint,1,opt,name=school_id,json=schoolId,proto3" json:"school_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSchoolIDResponse) Reset() {
	*x = GetSchoolIDResponse{}
	mi := &file_v1_school_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSchoolIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSchoolIDResponse) ProtoMessage() {}

func (x *GetSchoolIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_school_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSchoolIDResponse.ProtoReflect.Descriptor instead.
func (*GetSchoolIDResponse) Descriptor() ([]byte, []int) {
	return file_v1_school_api_proto_rawDescGZIP(), []int{1}
}

func (x *GetSchoolIDResponse) GetSchoolId() int64 {
	if x != nil {
		return x.SchoolId
	}
	return 0
}

var File_v1_school_api_proto protoreflect.FileDescriptor

const file_v1_school_api_proto_rawDesc = "" +
	"\n" +
	"\x13v1/school_api.proto\x12\tschool.v1\"-\n" +
	"\x12GetSchoolIDRequest\x12\x17\n" +
	"\aauth_id\x18\x01 \x01(\x03R\x06authId\"2\n" +
	"\x13GetSchoolIDResponse\x12\x1b\n" +
	"\tschool_id\x18\x01 \x01(\x03R\bschoolId2]\n" +
	"\rSchoolService\x12L\n" +
	"\vGetSchoolID\x12\x1d.school.v1.GetSchoolIDRequest\x1a\x1e.school.v1.GetSchoolIDResponseBAZ?github.com/ritchieridanko/klasshub/shared/contract/apis/v1;apisb\x06proto3"

var (
	file_v1_school_api_proto_rawDescOnce sync.Once
	file_v1_school_api_proto_rawDescData []byte
)

func file_v1_school_api_proto_rawDescGZIP() []byte {
	file_v1_school_api_proto_rawDescOnce.Do(func() {
		file_v1_school_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_school_api_proto_rawDesc), len(file_v1_school_api_proto_rawDesc)))
	})
	return file_v1_school_api_proto_rawDescData
}

var file_v1_school_api_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_v1_school_api_proto_goTypes = []any{
	(*GetSchoolIDRequest)(nil),  // 0: school.v1.GetSchoolIDRequest
	(*GetSchoolIDResponse)(nil), // 1: school.v1.GetSchoolIDResponse
}
var file_v1_school_api_proto_depIdxs = []int32{
	0, // 0: school.v1.SchoolService.GetSchoolID:input_type -> school.v1.GetSchoolIDRequest
	1, // 1: school.v1.SchoolService.GetSchoolID:output_type -> school.v1.GetSchoolIDResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v1_school_api_proto_init() }
func file_v1_school_api_proto_init() {
	if File_v1_school_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_school_api_proto_rawDesc), len(file_v1_school_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_school_api_proto_goTypes,
		DependencyIndexes: file_v1_school_api_proto_depIdxs,
		MessageInfos:      file_v1_school_api_proto_msgTypes,
	}.Build()
	File_v1_school_api_proto = out.File
	file_v1_school_api_proto_goTypes = nil
	file_v1_school_api_proto_depIdxs = nil
}
