// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.2
// source: v1/school_api.proto

package apis

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type School struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NPSN           *string                `protobuf:"bytes,1,opt,name=n_p_s_n,json=nPSN,proto3,oneof" json:"n_p_s_n,omitempty"`
	NPSNVerifiedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=n_p_s_n_verified_at,json=nPSNVerifiedAt,proto3" json:"n_p_s_n_verified_at,omitempty"`
	Name           string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Level          string                 `protobuf:"bytes,4,opt,name=level,proto3" json:"level,omitempty"`
	Ownership      string                 `protobuf:"bytes,5,opt,name=ownership,proto3" json:"ownership,omitempty"`
	ProfilePicture *string                `protobuf:"bytes,6,opt,name=profile_picture,json=profilePicture,proto3,oneof" json:"profile_picture,omitempty"`
	ProfileBanner  *string                `protobuf:"bytes,7,opt,name=profile_banner,json=profileBanner,proto3,oneof" json:"profile_banner,omitempty"`
	Accreditation  *string                `protobuf:"bytes,8,opt,name=accreditation,proto3,oneof" json:"accreditation,omitempty"`
	EstablishedAt  *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=established_at,json=establishedAt,proto3" json:"established_at,omitempty"`
	Province       string                 `protobuf:"bytes,10,opt,name=province,proto3" json:"province,omitempty"`
	CityRegency    string                 `protobuf:"bytes,11,opt,name=city_regency,json=cityRegency,proto3" json:"city_regency,omitempty"`
	District       string                 `protobuf:"bytes,12,opt,name=district,proto3" json:"district,omitempty"`
	Subdistrict    string                 `protobuf:"bytes,13,opt,name=subdistrict,proto3" json:"subdistrict,omitempty"`
	Street         string                 `protobuf:"bytes,14,opt,name=street,proto3" json:"street,omitempty"`
	Postcode       string                 `protobuf:"bytes,15,opt,name=postcode,proto3" json:"postcode,omitempty"`
	Phone          *string                `protobuf:"bytes,16,opt,name=phone,proto3,oneof" json:"phone,omitempty"`
	Email          *string                `protobuf:"bytes,17,opt,name=email,proto3,oneof" json:"email,omitempty"`
	Website        *string                `protobuf:"bytes,18,opt,name=website,proto3,oneof" json:"website,omitempty"`
	Timezone       string                 `protobuf:"bytes,19,opt,name=timezone,proto3" json:"timezone,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,20,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *School) Reset() {
	*x = School{}
	mi := &file_v1_school_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *School) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*School) ProtoMessage() {}

func (x *School) ProtoReflect() protoreflect.Message {
	mi := &file_v1_school_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use School.ProtoReflect.Descriptor instead.
func (*School) Descriptor() ([]byte, []int) {
	return file_v1_school_api_proto_rawDescGZIP(), []int{0}
}

func (x *School) GetNPSN() string {
	if x != nil && x.NPSN != nil {
		return *x.NPSN
	}
	return ""
}

func (x *School) GetNPSNVerifiedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.NPSNVerifiedAt
	}
	return nil
}

func (x *School) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *School) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *School) GetOwnership() string {
	if x != nil {
		return x.Ownership
	}
	return ""
}

func (x *School) GetProfilePicture() string {
	if x != nil && x.ProfilePicture != nil {
		return *x.ProfilePicture
	}
	return ""
}

func (x *School) GetProfileBanner() string {
	if x != nil && x.ProfileBanner != nil {
		return *x.ProfileBanner
	}
	return ""
}

func (x *School) GetAccreditation() string {
	if x != nil && x.Accreditation != nil {
		return *x.Accreditation
	}
	return ""
}

func (x *School) GetEstablishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EstablishedAt
	}
	return nil
}

func (x *School) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *School) GetCityRegency() string {
	if x != nil {
		return x.CityRegency
	}
	return ""
}

func (x *School) GetDistrict() string {
	if x != nil {
		return x.District
	}
	return ""
}

func (x *School) GetSubdistrict() string {
	if x != nil {
		return x.Subdistrict
	}
	return ""
}

func (x *School) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *School) GetPostcode() string {
	if x != nil {
		return x.Postcode
	}
	return ""
}

func (x *School) GetPhone() string {
	if x != nil && x.Phone != nil {
		return *x.Phone
	}
	return ""
}

func (x *School) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

func (x *School) GetWebsite() string {
	if x != nil && x.Website != nil {
		return *x.Website
	}
	return ""
}

func (x *School) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

func (x *School) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CreateSchoolRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NPSN          *string                `protobuf:"bytes,1,opt,name=n_p_s_n,json=nPSN,proto3,oneof" json:"n_p_s_n,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Level         string                 `protobuf:"bytes,3,opt,name=level,proto3" json:"level,omitempty"`
	Ownership     string                 `protobuf:"bytes,4,opt,name=ownership,proto3" json:"ownership,omitempty"`
	Accreditation *string                `protobuf:"bytes,5,opt,name=accreditation,proto3,oneof" json:"accreditation,omitempty"`
	EstablishedAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=established_at,json=establishedAt,proto3" json:"established_at,omitempty"`
	Province      string                 `protobuf:"bytes,7,opt,name=province,proto3" json:"province,omitempty"`
	CityRegency   string                 `protobuf:"bytes,8,opt,name=city_regency,json=cityRegency,proto3" json:"city_regency,omitempty"`
	District      string                 `protobuf:"bytes,9,opt,name=district,proto3" json:"district,omitempty"`
	Subdistrict   string                 `protobuf:"bytes,10,opt,name=subdistrict,proto3" json:"subdistrict,omitempty"`
	Street        string                 `protobuf:"bytes,11,opt,name=street,proto3" json:"street,omitempty"`
	Postcode      string                 `protobuf:"bytes,12,opt,name=postcode,proto3" json:"postcode,omitempty"`
	Phone         *string                `protobuf:"bytes,13,opt,name=phone,proto3,oneof" json:"phone,omitempty"`
	Email         *string                `protobuf:"bytes,14,opt,name=email,proto3,oneof" json:"email,omitempty"`
	Website       *string                `protobuf:"bytes,15,opt,name=website,proto3,oneof" json:"website,omitempty"`
	Timezone      string                 `protobuf:"bytes,16,opt,name=timezone,proto3" json:"timezone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSchoolRequest) Reset() {
	*x = CreateSchoolRequest{}
	mi := &file_v1_school_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSchoolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSchoolRequest) ProtoMessage() {}

func (x *CreateSchoolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_school_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSchoolRequest.ProtoReflect.Descriptor instead.
func (*CreateSchoolRequest) Descriptor() ([]byte, []int) {
	return file_v1_school_api_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSchoolRequest) GetNPSN() string {
	if x != nil && x.NPSN != nil {
		return *x.NPSN
	}
	return ""
}

func (x *CreateSchoolRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateSchoolRequest) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *CreateSchoolRequest) GetOwnership() string {
	if x != nil {
		return x.Ownership
	}
	return ""
}

func (x *CreateSchoolRequest) GetAccreditation() string {
	if x != nil && x.Accreditation != nil {
		return *x.Accreditation
	}
	return ""
}

func (x *CreateSchoolRequest) GetEstablishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EstablishedAt
	}
	return nil
}

func (x *CreateSchoolRequest) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *CreateSchoolRequest) GetCityRegency() string {
	if x != nil {
		return x.CityRegency
	}
	return ""
}

func (x *CreateSchoolRequest) GetDistrict() string {
	if x != nil {
		return x.District
	}
	return ""
}

func (x *CreateSchoolRequest) GetSubdistrict() string {
	if x != nil {
		return x.Subdistrict
	}
	return ""
}

func (x *CreateSchoolRequest) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *CreateSchoolRequest) GetPostcode() string {
	if x != nil {
		return x.Postcode
	}
	return ""
}

func (x *CreateSchoolRequest) GetPhone() string {
	if x != nil && x.Phone != nil {
		return *x.Phone
	}
	return ""
}

func (x *CreateSchoolRequest) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

func (x *CreateSchoolRequest) GetWebsite() string {
	if x != nil && x.Website != nil {
		return *x.Website
	}
	return ""
}

func (x *CreateSchoolRequest) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

type CreateSchoolResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchoolId      int64                  `protobuf:"varint,1,opt,name=school_id,json=schoolId,proto3" json:"school_id,omitempty"`
	School        *School                `protobuf:"bytes,2,opt,name=school,proto3" json:"school,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSchoolResponse) Reset() {
	*x = CreateSchoolResponse{}
	mi := &file_v1_school_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSchoolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSchoolResponse) ProtoMessage() {}

func (x *CreateSchoolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_school_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSchoolResponse.ProtoReflect.Descriptor instead.
func (*CreateSchoolResponse) Descriptor() ([]byte, []int) {
	return file_v1_school_api_proto_rawDescGZIP(), []int{2}
}

func (x *CreateSchoolResponse) GetSchoolId() int64 {
	if x != nil {
		return x.SchoolId
	}
	return 0
}

func (x *CreateSchoolResponse) GetSchool() *School {
	if x != nil {
		return x.School
	}
	return nil
}

type SchoolGetMeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	School        *School                `protobuf:"bytes,1,opt,name=school,proto3" json:"school,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SchoolGetMeResponse) Reset() {
	*x = SchoolGetMeResponse{}
	mi := &file_v1_school_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchoolGetMeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchoolGetMeResponse) ProtoMessage() {}

func (x *SchoolGetMeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_school_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchoolGetMeResponse.ProtoReflect.Descriptor instead.
func (*SchoolGetMeResponse) Descriptor() ([]byte, []int) {
	return file_v1_school_api_proto_rawDescGZIP(), []int{3}
}

func (x *SchoolGetMeResponse) GetSchool() *School {
	if x != nil {
		return x.School
	}
	return nil
}

type SchoolExistenceCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchoolId      int64                  `protobuf:"varint,1,opt,name=school_id,json=schoolId,proto3" json:"school_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SchoolExistenceCheckRequest) Reset() {
	*x = SchoolExistenceCheckRequest{}
	mi := &file_v1_school_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchoolExistenceCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchoolExistenceCheckRequest) ProtoMessage() {}

func (x *SchoolExistenceCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_school_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchoolExistenceCheckRequest.ProtoReflect.Descriptor instead.
func (*SchoolExistenceCheckRequest) Descriptor() ([]byte, []int) {
	return file_v1_school_api_proto_rawDescGZIP(), []int{4}
}

func (x *SchoolExistenceCheckRequest) GetSchoolId() int64 {
	if x != nil {
		return x.SchoolId
	}
	return 0
}

type SchoolExistenceCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SchoolExistenceCheckResponse) Reset() {
	*x = SchoolExistenceCheckResponse{}
	mi := &file_v1_school_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchoolExistenceCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchoolExistenceCheckResponse) ProtoMessage() {}

func (x *SchoolExistenceCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_school_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchoolExistenceCheckResponse.ProtoReflect.Descriptor instead.
func (*SchoolExistenceCheckResponse) Descriptor() ([]byte, []int) {
	return file_v1_school_api_proto_rawDescGZIP(), []int{5}
}

func (x *SchoolExistenceCheckResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

var File_v1_school_api_proto protoreflect.FileDescriptor

const file_v1_school_api_proto_rawDesc = "" +
	"\n" +
	"\x13v1/school_api.proto\x12\tschool.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbf\x06\n" +
	"\x06School\x12\x1a\n" +
	"\an_p_s_n\x18\x01 \x01(\tH\x00R\x04nPSN\x88\x01\x01\x12G\n" +
	"\x13n_p_s_n_verified_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x0enPSNVerifiedAt\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05level\x18\x04 \x01(\tR\x05level\x12\x1c\n" +
	"\townership\x18\x05 \x01(\tR\townership\x12,\n" +
	"\x0fprofile_picture\x18\x06 \x01(\tH\x01R\x0eprofilePicture\x88\x01\x01\x12*\n" +
	"\x0eprofile_banner\x18\a \x01(\tH\x02R\rprofileBanner\x88\x01\x01\x12)\n" +
	"\raccreditation\x18\b \x01(\tH\x03R\raccreditation\x88\x01\x01\x12A\n" +
	"\x0eestablished_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\restablishedAt\x12\x1a\n" +
	"\bprovince\x18\n" +
	" \x01(\tR\bprovince\x12!\n" +
	"\fcity_regency\x18\v \x01(\tR\vcityRegency\x12\x1a\n" +
	"\bdistrict\x18\f \x01(\tR\bdistrict\x12 \n" +
	"\vsubdistrict\x18\r \x01(\tR\vsubdistrict\x12\x16\n" +
	"\x06street\x18\x0e \x01(\tR\x06street\x12\x1a\n" +
	"\bpostcode\x18\x0f \x01(\tR\bpostcode\x12\x19\n" +
	"\x05phone\x18\x10 \x01(\tH\x04R\x05phone\x88\x01\x01\x12\x19\n" +
	"\x05email\x18\x11 \x01(\tH\x05R\x05email\x88\x01\x01\x12\x1d\n" +
	"\awebsite\x18\x12 \x01(\tH\x06R\awebsite\x88\x01\x01\x12\x1a\n" +
	"\btimezone\x18\x13 \x01(\tR\btimezone\x129\n" +
	"\n" +
	"created_at\x18\x14 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAtB\n" +
	"\n" +
	"\b_n_p_s_nB\x12\n" +
	"\x10_profile_pictureB\x11\n" +
	"\x0f_profile_bannerB\x10\n" +
	"\x0e_accreditationB\b\n" +
	"\x06_phoneB\b\n" +
	"\x06_emailB\n" +
	"\n" +
	"\b_website\"\xc7\x04\n" +
	"\x13CreateSchoolRequest\x12\x1a\n" +
	"\an_p_s_n\x18\x01 \x01(\tH\x00R\x04nPSN\x88\x01\x01\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05level\x18\x03 \x01(\tR\x05level\x12\x1c\n" +
	"\townership\x18\x04 \x01(\tR\townership\x12)\n" +
	"\raccreditation\x18\x05 \x01(\tH\x01R\raccreditation\x88\x01\x01\x12A\n" +
	"\x0eestablished_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\restablishedAt\x12\x1a\n" +
	"\bprovince\x18\a \x01(\tR\bprovince\x12!\n" +
	"\fcity_regency\x18\b \x01(\tR\vcityRegency\x12\x1a\n" +
	"\bdistrict\x18\t \x01(\tR\bdistrict\x12 \n" +
	"\vsubdistrict\x18\n" +
	" \x01(\tR\vsubdistrict\x12\x16\n" +
	"\x06street\x18\v \x01(\tR\x06street\x12\x1a\n" +
	"\bpostcode\x18\f \x01(\tR\bpostcode\x12\x19\n" +
	"\x05phone\x18\r \x01(\tH\x02R\x05phone\x88\x01\x01\x12\x19\n" +
	"\x05email\x18\x0e \x01(\tH\x03R\x05email\x88\x01\x01\x12\x1d\n" +
	"\awebsite\x18\x0f \x01(\tH\x04R\awebsite\x88\x01\x01\x12\x1a\n" +
	"\btimezone\x18\x10 \x01(\tR\btimezoneB\n" +
	"\n" +
	"\b_n_p_s_nB\x10\n" +
	"\x0e_accreditationB\b\n" +
	"\x06_phoneB\b\n" +
	"\x06_emailB\n" +
	"\n" +
	"\b_website\"^\n" +
	"\x14CreateSchoolResponse\x12\x1b\n" +
	"\tschool_id\x18\x01 \x01(\x03R\bschoolId\x12)\n" +
	"\x06school\x18\x02 \x01(\v2\x11.school.v1.SchoolR\x06school\"@\n" +
	"\x13SchoolGetMeResponse\x12)\n" +
	"\x06school\x18\x01 \x01(\v2\x11.school.v1.SchoolR\x06school\":\n" +
	"\x1bSchoolExistenceCheckRequest\x12\x1b\n" +
	"\tschool_id\x18\x01 \x01(\x03R\bschoolId\"6\n" +
	"\x1cSchoolExistenceCheckResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists2\x82\x02\n" +
	"\rSchoolService\x12O\n" +
	"\fCreateSchool\x12\x1e.school.v1.CreateSchoolRequest\x1a\x1f.school.v1.CreateSchoolResponse\x12?\n" +
	"\x05GetMe\x12\x16.google.protobuf.Empty\x1a\x1e.school.v1.SchoolGetMeResponse\x12_\n" +
	"\fSchoolExists\x12&.school.v1.SchoolExistenceCheckRequest\x1a'.school.v1.SchoolExistenceCheckResponseBAZ?github.com/ritchieridanko/klasshub/shared/contract/apis/v1;apisb\x06proto3"

var (
	file_v1_school_api_proto_rawDescOnce sync.Once
	file_v1_school_api_proto_rawDescData []byte
)

func file_v1_school_api_proto_rawDescGZIP() []byte {
	file_v1_school_api_proto_rawDescOnce.Do(func() {
		file_v1_school_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_school_api_proto_rawDesc), len(file_v1_school_api_proto_rawDesc)))
	})
	return file_v1_school_api_proto_rawDescData
}

var file_v1_school_api_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_v1_school_api_proto_goTypes = []any{
	(*School)(nil),                       // 0: school.v1.School
	(*CreateSchoolRequest)(nil),          // 1: school.v1.CreateSchoolRequest
	(*CreateSchoolResponse)(nil),         // 2: school.v1.CreateSchoolResponse
	(*SchoolGetMeResponse)(nil),          // 3: school.v1.SchoolGetMeResponse
	(*SchoolExistenceCheckRequest)(nil),  // 4: school.v1.SchoolExistenceCheckRequest
	(*SchoolExistenceCheckResponse)(nil), // 5: school.v1.SchoolExistenceCheckResponse
	(*timestamppb.Timestamp)(nil),        // 6: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                // 7: google.protobuf.Empty
}
var file_v1_school_api_proto_depIdxs = []int32{
	6, // 0: school.v1.School.n_p_s_n_verified_at:type_name -> google.protobuf.Timestamp
	6, // 1: school.v1.School.established_at:type_name -> google.protobuf.Timestamp
	6, // 2: school.v1.School.created_at:type_name -> google.protobuf.Timestamp
	6, // 3: school.v1.CreateSchoolRequest.established_at:type_name -> google.protobuf.Timestamp
	0, // 4: school.v1.CreateSchoolResponse.school:type_name -> school.v1.School
	0, // 5: school.v1.SchoolGetMeResponse.school:type_name -> school.v1.School
	1, // 6: school.v1.SchoolService.CreateSchool:input_type -> school.v1.CreateSchoolRequest
	7, // 7: school.v1.SchoolService.GetMe:input_type -> google.protobuf.Empty
	4, // 8: school.v1.SchoolService.SchoolExists:input_type -> school.v1.SchoolExistenceCheckRequest
	2, // 9: school.v1.SchoolService.CreateSchool:output_type -> school.v1.CreateSchoolResponse
	3, // 10: school.v1.SchoolService.GetMe:output_type -> school.v1.SchoolGetMeResponse
	5, // 11: school.v1.SchoolService.SchoolExists:output_type -> school.v1.SchoolExistenceCheckResponse
	9, // [9:12] is the sub-list for method output_type
	6, // [6:9] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_v1_school_api_proto_init() }
func file_v1_school_api_proto_init() {
	if File_v1_school_api_proto != nil {
		return
	}
	file_v1_school_api_proto_msgTypes[0].OneofWrappers = []any{}
	file_v1_school_api_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_school_api_proto_rawDesc), len(file_v1_school_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_school_api_proto_goTypes,
		DependencyIndexes: file_v1_school_api_proto_depIdxs,
		MessageInfos:      file_v1_school_api_proto_msgTypes,
	}.Build()
	File_v1_school_api_proto = out.File
	file_v1_school_api_proto_goTypes = nil
	file_v1_school_api_proto_depIdxs = nil
}
