// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: v1/user_api.proto

package apis

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SchoolUserId   *wrappers.StringValue  `protobuf:"bytes,2,opt,name=school_user_id,json=schoolUserId,proto3" json:"school_user_id,omitempty"`
	Role           string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	Name           string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Nickname       *wrappers.StringValue  `protobuf:"bytes,5,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Birthplace     *wrappers.StringValue  `protobuf:"bytes,6,opt,name=birthplace,proto3" json:"birthplace,omitempty"`
	Birthdate      *timestamp.Timestamp   `protobuf:"bytes,7,opt,name=birthdate,proto3" json:"birthdate,omitempty"`
	Sex            *wrappers.StringValue  `protobuf:"bytes,8,opt,name=sex,proto3" json:"sex,omitempty"`
	Phone          *wrappers.StringValue  `protobuf:"bytes,9,opt,name=phone,proto3" json:"phone,omitempty"`
	ProfilePicture *wrappers.StringValue  `protobuf:"bytes,10,opt,name=profile_picture,json=profilePicture,proto3" json:"profile_picture,omitempty"`
	ProfileBanner  *wrappers.StringValue  `protobuf:"bytes,11,opt,name=profile_banner,json=profileBanner,proto3" json:"profile_banner,omitempty"`
	CreatedBy      *wrappers.StringValue  `protobuf:"bytes,12,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	CreatedByName  *wrappers.StringValue  `protobuf:"bytes,13,opt,name=created_by_name,json=createdByName,proto3" json:"created_by_name,omitempty"`
	CreatedAt      *timestamp.Timestamp   `protobuf:"bytes,14,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamp.Timestamp   `protobuf:"bytes,15,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt      *timestamp.Timestamp   `protobuf:"bytes,16,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_v1_user_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_v1_user_api_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetSchoolUserId() *wrappers.StringValue {
	if x != nil {
		return x.SchoolUserId
	}
	return nil
}

func (x *User) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetNickname() *wrappers.StringValue {
	if x != nil {
		return x.Nickname
	}
	return nil
}

func (x *User) GetBirthplace() *wrappers.StringValue {
	if x != nil {
		return x.Birthplace
	}
	return nil
}

func (x *User) GetBirthdate() *timestamp.Timestamp {
	if x != nil {
		return x.Birthdate
	}
	return nil
}

func (x *User) GetSex() *wrappers.StringValue {
	if x != nil {
		return x.Sex
	}
	return nil
}

func (x *User) GetPhone() *wrappers.StringValue {
	if x != nil {
		return x.Phone
	}
	return nil
}

func (x *User) GetProfilePicture() *wrappers.StringValue {
	if x != nil {
		return x.ProfilePicture
	}
	return nil
}

func (x *User) GetProfileBanner() *wrappers.StringValue {
	if x != nil {
		return x.ProfileBanner
	}
	return nil
}

func (x *User) GetCreatedBy() *wrappers.StringValue {
	if x != nil {
		return x.CreatedBy
	}
	return nil
}

func (x *User) GetCreatedByName() *wrappers.StringValue {
	if x != nil {
		return x.CreatedByName
	}
	return nil
}

func (x *User) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *User) GetUpdatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *User) GetDeletedAt() *timestamp.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthId        int64                  `protobuf:"varint,1,opt,name=auth_id,json=authId,proto3" json:"auth_id,omitempty"`
	SchoolId      int64                  `protobuf:"varint,2,opt,name=school_id,json=schoolId,proto3" json:"school_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_v1_user_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_v1_user_api_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserRequest) GetAuthId() int64 {
	if x != nil {
		return x.AuthId
	}
	return 0
}

func (x *GetUserRequest) GetSchoolId() int64 {
	if x != nil {
		return x.SchoolId
	}
	return 0
}

type GetUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserResponse) Reset() {
	*x = GetUserResponse{}
	mi := &file_v1_user_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResponse) ProtoMessage() {}

func (x *GetUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResponse.ProtoReflect.Descriptor instead.
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return file_v1_user_api_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

var File_v1_user_api_proto protoreflect.FileDescriptor

const file_v1_user_api_proto_rawDesc = "" +
	"\n" +
	"\x11v1/user_api.proto\x12\auser.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\xd8\x06\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12B\n" +
	"\x0eschool_user_id\x18\x02 \x01(\v2\x1c.google.protobuf.StringValueR\fschoolUserId\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x128\n" +
	"\bnickname\x18\x05 \x01(\v2\x1c.google.protobuf.StringValueR\bnickname\x12<\n" +
	"\n" +
	"birthplace\x18\x06 \x01(\v2\x1c.google.protobuf.StringValueR\n" +
	"birthplace\x128\n" +
	"\tbirthdate\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tbirthdate\x12.\n" +
	"\x03sex\x18\b \x01(\v2\x1c.google.protobuf.StringValueR\x03sex\x122\n" +
	"\x05phone\x18\t \x01(\v2\x1c.google.protobuf.StringValueR\x05phone\x12E\n" +
	"\x0fprofile_picture\x18\n" +
	" \x01(\v2\x1c.google.protobuf.StringValueR\x0eprofilePicture\x12C\n" +
	"\x0eprofile_banner\x18\v \x01(\v2\x1c.google.protobuf.StringValueR\rprofileBanner\x12;\n" +
	"\n" +
	"created_by\x18\f \x01(\v2\x1c.google.protobuf.StringValueR\tcreatedBy\x12D\n" +
	"\x0fcreated_by_name\x18\r \x01(\v2\x1c.google.protobuf.StringValueR\rcreatedByName\x129\n" +
	"\n" +
	"created_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"deleted_at\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\"F\n" +
	"\x0eGetUserRequest\x12\x17\n" +
	"\aauth_id\x18\x01 \x01(\x03R\x06authId\x12\x1b\n" +
	"\tschool_id\x18\x02 \x01(\x03R\bschoolId\"4\n" +
	"\x0fGetUserResponse\x12!\n" +
	"\x04user\x18\x01 \x01(\v2\r.user.v1.UserR\x04user2K\n" +
	"\vUserService\x12<\n" +
	"\aGetUser\x12\x17.user.v1.GetUserRequest\x1a\x18.user.v1.GetUserResponseBAZ?github.com/ritchieridanko/klasshub/shared/contract/apis/v1;apisb\x06proto3"

var (
	file_v1_user_api_proto_rawDescOnce sync.Once
	file_v1_user_api_proto_rawDescData []byte
)

func file_v1_user_api_proto_rawDescGZIP() []byte {
	file_v1_user_api_proto_rawDescOnce.Do(func() {
		file_v1_user_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_user_api_proto_rawDesc), len(file_v1_user_api_proto_rawDesc)))
	})
	return file_v1_user_api_proto_rawDescData
}

var file_v1_user_api_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_v1_user_api_proto_goTypes = []any{
	(*User)(nil),                 // 0: user.v1.User
	(*GetUserRequest)(nil),       // 1: user.v1.GetUserRequest
	(*GetUserResponse)(nil),      // 2: user.v1.GetUserResponse
	(*wrappers.StringValue)(nil), // 3: google.protobuf.StringValue
	(*timestamp.Timestamp)(nil),  // 4: google.protobuf.Timestamp
}
var file_v1_user_api_proto_depIdxs = []int32{
	3,  // 0: user.v1.User.school_user_id:type_name -> google.protobuf.StringValue
	3,  // 1: user.v1.User.nickname:type_name -> google.protobuf.StringValue
	3,  // 2: user.v1.User.birthplace:type_name -> google.protobuf.StringValue
	4,  // 3: user.v1.User.birthdate:type_name -> google.protobuf.Timestamp
	3,  // 4: user.v1.User.sex:type_name -> google.protobuf.StringValue
	3,  // 5: user.v1.User.phone:type_name -> google.protobuf.StringValue
	3,  // 6: user.v1.User.profile_picture:type_name -> google.protobuf.StringValue
	3,  // 7: user.v1.User.profile_banner:type_name -> google.protobuf.StringValue
	3,  // 8: user.v1.User.created_by:type_name -> google.protobuf.StringValue
	3,  // 9: user.v1.User.created_by_name:type_name -> google.protobuf.StringValue
	4,  // 10: user.v1.User.created_at:type_name -> google.protobuf.Timestamp
	4,  // 11: user.v1.User.updated_at:type_name -> google.protobuf.Timestamp
	4,  // 12: user.v1.User.deleted_at:type_name -> google.protobuf.Timestamp
	0,  // 13: user.v1.GetUserResponse.user:type_name -> user.v1.User
	1,  // 14: user.v1.UserService.GetUser:input_type -> user.v1.GetUserRequest
	2,  // 15: user.v1.UserService.GetUser:output_type -> user.v1.GetUserResponse
	15, // [15:16] is the sub-list for method output_type
	14, // [14:15] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_v1_user_api_proto_init() }
func file_v1_user_api_proto_init() {
	if File_v1_user_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_user_api_proto_rawDesc), len(file_v1_user_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_user_api_proto_goTypes,
		DependencyIndexes: file_v1_user_api_proto_depIdxs,
		MessageInfos:      file_v1_user_api_proto_msgTypes,
	}.Build()
	File_v1_user_api_proto = out.File
	file_v1_user_api_proto_goTypes = nil
	file_v1_user_api_proto_depIdxs = nil
}
