// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.2
// source: v1/auth_event.proto

package events

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthCreated struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	EventId           string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Role              string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	Email             string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	VerificationToken string                 `protobuf:"bytes,4,opt,name=verification_token,json=verificationToken,proto3" json:"verification_token,omitempty"`
	CreatedAt         *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AuthCreated) Reset() {
	*x = AuthCreated{}
	mi := &file_v1_auth_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthCreated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthCreated) ProtoMessage() {}

func (x *AuthCreated) ProtoReflect() protoreflect.Message {
	mi := &file_v1_auth_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthCreated.ProtoReflect.Descriptor instead.
func (*AuthCreated) Descriptor() ([]byte, []int) {
	return file_v1_auth_event_proto_rawDescGZIP(), []int{0}
}

func (x *AuthCreated) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *AuthCreated) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *AuthCreated) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AuthCreated) GetVerificationToken() string {
	if x != nil {
		return x.VerificationToken
	}
	return ""
}

func (x *AuthCreated) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type AuthSchoolUpdateFailed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	SchoolId      int64                  `protobuf:"varint,2,opt,name=school_id,json=schoolId,proto3" json:"school_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthSchoolUpdateFailed) Reset() {
	*x = AuthSchoolUpdateFailed{}
	mi := &file_v1_auth_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthSchoolUpdateFailed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthSchoolUpdateFailed) ProtoMessage() {}

func (x *AuthSchoolUpdateFailed) ProtoReflect() protoreflect.Message {
	mi := &file_v1_auth_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthSchoolUpdateFailed.ProtoReflect.Descriptor instead.
func (*AuthSchoolUpdateFailed) Descriptor() ([]byte, []int) {
	return file_v1_auth_event_proto_rawDescGZIP(), []int{1}
}

func (x *AuthSchoolUpdateFailed) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *AuthSchoolUpdateFailed) GetSchoolId() int64 {
	if x != nil {
		return x.SchoolId
	}
	return 0
}

func (x *AuthSchoolUpdateFailed) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type AuthVerificationRequested struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	EventId           string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Role              string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	Email             string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	VerificationToken string                 `protobuf:"bytes,4,opt,name=verification_token,json=verificationToken,proto3" json:"verification_token,omitempty"`
	CreatedAt         *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AuthVerificationRequested) Reset() {
	*x = AuthVerificationRequested{}
	mi := &file_v1_auth_event_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthVerificationRequested) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthVerificationRequested) ProtoMessage() {}

func (x *AuthVerificationRequested) ProtoReflect() protoreflect.Message {
	mi := &file_v1_auth_event_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthVerificationRequested.ProtoReflect.Descriptor instead.
func (*AuthVerificationRequested) Descriptor() ([]byte, []int) {
	return file_v1_auth_event_proto_rawDescGZIP(), []int{2}
}

func (x *AuthVerificationRequested) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *AuthVerificationRequested) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *AuthVerificationRequested) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AuthVerificationRequested) GetVerificationToken() string {
	if x != nil {
		return x.VerificationToken
	}
	return ""
}

func (x *AuthVerificationRequested) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_v1_auth_event_proto protoreflect.FileDescriptor

const file_v1_auth_event_proto_rawDesc = "" +
	"\n" +
	"\x13v1/auth_event.proto\x12\aauth.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbc\x01\n" +
	"\vAuthCreated\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12-\n" +
	"\x12verification_token\x18\x04 \x01(\tR\x11verificationToken\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x8b\x01\n" +
	"\x16AuthSchoolUpdateFailed\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1b\n" +
	"\tschool_id\x18\x02 \x01(\x03R\bschoolId\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xca\x01\n" +
	"\x19AuthVerificationRequested\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12-\n" +
	"\x12verification_token\x18\x04 \x01(\tR\x11verificationToken\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAtBEZCgithub.com/ritchieridanko/klasshub/shared/contract/events/v1;eventsb\x06proto3"

var (
	file_v1_auth_event_proto_rawDescOnce sync.Once
	file_v1_auth_event_proto_rawDescData []byte
)

func file_v1_auth_event_proto_rawDescGZIP() []byte {
	file_v1_auth_event_proto_rawDescOnce.Do(func() {
		file_v1_auth_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_auth_event_proto_rawDesc), len(file_v1_auth_event_proto_rawDesc)))
	})
	return file_v1_auth_event_proto_rawDescData
}

var file_v1_auth_event_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_v1_auth_event_proto_goTypes = []any{
	(*AuthCreated)(nil),               // 0: auth.v1.AuthCreated
	(*AuthSchoolUpdateFailed)(nil),    // 1: auth.v1.AuthSchoolUpdateFailed
	(*AuthVerificationRequested)(nil), // 2: auth.v1.AuthVerificationRequested
	(*timestamppb.Timestamp)(nil),     // 3: google.protobuf.Timestamp
}
var file_v1_auth_event_proto_depIdxs = []int32{
	3, // 0: auth.v1.AuthCreated.created_at:type_name -> google.protobuf.Timestamp
	3, // 1: auth.v1.AuthSchoolUpdateFailed.created_at:type_name -> google.protobuf.Timestamp
	3, // 2: auth.v1.AuthVerificationRequested.created_at:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_v1_auth_event_proto_init() }
func file_v1_auth_event_proto_init() {
	if File_v1_auth_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_auth_event_proto_rawDesc), len(file_v1_auth_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_auth_event_proto_goTypes,
		DependencyIndexes: file_v1_auth_event_proto_depIdxs,
		MessageInfos:      file_v1_auth_event_proto_msgTypes,
	}.Build()
	File_v1_auth_event_proto = out.File
	file_v1_auth_event_proto_goTypes = nil
	file_v1_auth_event_proto_depIdxs = nil
}
