app:
  name: "school-service"

server:
  host: "localhost"
  port: 50053
  timeout:
    shutdown: "10s"

database:
  host: "localhost"
  port: 5432
  user: ""
  pass: ""
  name: "klasshub_school_db"
  ssl_mode: "disable"
  max_conns: 5
  min_conns: 1
  max_conn_lifetime: "1h"
  max_conn_idle_time: "30m"

broker:
  brokers: "localhost:9092,localhost:9093,localhost:9094"
  subscriber:
    auth_school_update_failed:
      name: "auth.school.update.failed"
      max_bytes: 1000000
      max_wait: "10s"
      commit_interval: "1s"
      process_timeout: "5s"

tracer:
  host: "localhost"
  port: 4317
