app:
  name: "gateway-service"

client:
  host: "localhost"
  port: 3000

server:
  host: "localhost"
  port: 8080
  timeout:
    read: "5s"
    write: "5s"
    shutdown: "10s"

service:
  auth:
    name: "auth-service"
    host: "localhost"
    port: 50051
  account:
    name: "account-service"
    host: "localhost"
    port: 50052
  school:
    name: "school-service"
    host: "localhost"
    port: 50053
  user:
    name: "user-service"
    host: "localhost"
    port: 50054

tracer:
  host: "localhost"
  port: 4317

jwt:
  secret: ""
